"""Writes notes/PAPER_BRIEF.md from results/processed/paper_numbers.json.

Every figure in the brief comes from that JSON, so the brief cannot drift away
from the paper's numbers. Run it after make_paper_numbers.py.
"""
import json
from pathlib import Path

N = json.load(open("results/processed/paper_numbers.json"))
E, ds = N["external"], N["dataset"]

g_ctx = {i: N["in_context"]["generation_olmo2"][str(i)][2] for i in (2, 3, 4, 5)}
g_iso = {i: N["isolated"]["generation_olmo2"][str(i)][2] for i in (2, 3, 4, 5)}
p8 = {i: E["patchscopes_8L_union_in_context_pct"][str(i)] for i in (2, 3, 4, 5)}
p32 = {i: N["in_context"]["patchscopes_olmo2_32L"][str(i)][2] for i in (2, 3, 4, 5)}
p_iso = {i: N["isolated"]["patchscopes_olmo2_32L"][str(i)][2] for i in (2, 3, 4, 5)}
ag8, ag32 = E["agreement_8L_pooled_i2_5"], N["agreement_32L_pooled_i2_5"]
cat8 = E["category_8L_pooled_i2_5_pct"]
catg = {k: v["success_pct"] for k, v in N["category_pooled_i2_5"]["generation"].items()}
cat32 = {k: v["success_pct"] for k, v in N["category_pooled_i2_5"]["patchscopes_32L"].items()}
ge = E["generation_label_probe"]
pp = N["per_phrase_consistency_i3"]["generation"]
fp, fpc = E["false_positive_llm_judgement"], E["false_positive_by_model_confidence"]
corr = N["probe_phrase_correlation"]["by_layer_i3"]
j = lambda d: " / ".join(str(d[i]) for i in (2, 3, 4, 5))

md = f"""# Paper brief

A claim-and-evidence map for the paper. Written by `code/make_paper_brief.py`
from `results/processed/paper_numbers.json`, so the numerical values below come
from the same source as the paper's. If the two ever disagree, the JSON is
authoritative. Do not edit this file by hand; edit the script.

## Identity

- Title: Do Language Models Recognize a Phrase Before Reading It?
- Amirim final project (HUJI, CS 68101), written in ACL format so it can be
  extended toward a future ACL-style submission. No venue or deadline is fixed,
  so no page limit binds.
- Type: empirical study with a small methodological contribution.
- Intended reader: an NLP reader who knows how language models work but nothing
  about this project. Plain words over fancy ones, short sentences, no term used
  before it is defined.

## One sentence

When a language model is partway through a familiar multi-word expression, does
its hidden state already carry enough information to recover the rest?

## Data

- {ds['phrases_total']:,} fixed expressions: {ds['phrases_by_category_source']['idiom']} idioms,
  {ds['phrases_by_category_source']['building']} landmarks, {ds['phrases_by_category_source']['movie']} film titles.
- {ds['context_instances']:,} distinct (phrase, context) pairs from FineWeb-Edu, covering
  {ds['phrases_with_at_least_one_context']:,} phrases. Repeated contexts are collapsed; only {ds['phrases_with_10_contexts']}
  phrases reach the full ten.
- {ag8['n']:,} trials at `i` in 2..5.

## Claims and evidence

| Claim | Evidence | Where | Scope or caveat |
|---|---|---|---|
| Familiar phrases are recovered several tokens early | Patchscopes, in context, `i`=2/3/4/5 | `external.patchscopes_8L_union_in_context_pct`: {j(p8)} | Eight probed layers, the budget used throughout the paper |
| The model's own continuation recovers more | Generation, in context | `in_context.generation_olmo2`: {j(g_ctx)} | Generation is the baseline, not a second reading of the state |
| Natural context raises recovery a lot | Same phrases, isolated vs in context | generation {j(g_iso)} isolated; Patchscopes 32L {j(p_iso)} isolated vs {j(p32)} in context | Isolation is not the natural operating condition |
| Outcomes cluster strongly by phrase | Per-phrase success vs a binomial null | `per_phrase_consistency_i3`: {pp['observed_pct']['at_least_90']}% of phrases recovered in >=90% of contexts against a null of {pp['binomial_null_pct']['at_least_90']}% | At `i`=3 over the {pp['phrases_with_at_least_5_distinct_contexts']} phrases with >=5 distinct contexts. Shows clustering, **not** that phrase identity causes it: frequency, length, tokenization, category and context similarity are not separated |
| A probe on one hidden state predicts completion | MLP on a single hidden state, generation label | `external.generation_label_probe`: {ge['balanced_accuracy_pct']['30']}% balanced accuracy, {ge['precision_pct']['30']}% precision at L30 | One phrase-level split at seed 42; features are standardised before training. Not recomputable from this repo, the feature arrays stay on the cluster |
| The two measurements mostly agree | Matched instances | `external.agreement_8L_pooled_i2_5`: {ag8['agreement_pct']}% agreement, {ag8['generation_only_pct']}% generation-only, {ag8['patchscopes_only_pct']}% Patchscopes-only | Widening to 32 layers lifts agreement to {ag32['agreement_pct']}% |
| The layer budget moves Patchscopes rates | 8 layers vs all 32 | {j(p8)} against {j(p32)} | Six to eight points. Always state which budget a Patchscopes rate used |
| The two rank categories differently | Same categories, both measurements | `external.category_8L_pooled_i2_5_pct` and `category_pooled_i2_5` | Patchscopes 8L: movie {cat8['movie']} > idiom {cat8['idiom']} > building {cat8['building']}. Generation: movie {catg['movie']} > building {catg['building']} > idiom {catg['idiom']}. Film titles lead under both; landmarks and idioms swap. The 32L sweep gives the same ordering as 8L (movie {cat32['movie']} > idiom {cat32['idiom']} > building {cat32['building']}) |
| Exact matching understates real knowledge | Judge over the probe's false positives | `external.false_positive_llm_judgement`: {fp['valid_alternate_pct']}% valid alternate, {fp['partially_right_pct']}% partially right, {fp['unrelated_pct']}% unrelated, n={fp['n']} | One automatic judge (ChatGPT, GPT-5.6 Sol), no human validation. Probe-selected, not a sample of all failures, so it does not correct the headline rates. The judge-free confidence split agrees: {fpc['model_confident_gt_0_7_pct']}% of those cases had model confidence above 0.7 |
| Probe confidence tracks phrase identity | Correlation with true per-phrase rate | `probe_phrase_correlation.by_layer_i3`: peaks at r={corr['10']} (L10), {corr['5']} at L5, {corr['30']} at L30 | Patchscopes label only; the equivalent on generation-label features was not run |

## Terminology

| Concept | Use | Avoid |
|---|---|---|
| Tokens still unread at the cut | **lookahead distance `i`** | "position", "offset" |
| Reading a hidden state via an injected prompt | **Patchscopes** | "readout"; "the model knows" without qualification |
| Greedy continuation from the true prefix | **generation**, our **baseline** | "readout"; "ground truth" |
| Holding information about tokens not yet read | **looking ahead / lookahead** | "anticipation" |
| A phrase recovered at some layer | **recovered / recognized at distance `i`** | "predicted" |
| Fixed multi-word expression | **phrase** | "entity", "collocation" |

## Settled

- **Primary Patchscopes budget: eight layers**, the set on which the per-layer,
  per-category and probing analyses were run. The 32-layer sweep is reported
  alongside wherever it exists.
- **Contexts are deduplicated.** The collection originally repeated contexts;
  every affected measurement was rerun on the deduplicated set in September 2026.
- **The Patchscopes-versus-generation comparison is a caveat, not a headline.**
  It is out of the abstract and introduction and short in 5.3.
- **The category comparison is computed over `i` in 2..5**, as its caption says.
  Computed over all distances instead, idioms would appear to lead; that was an
  artifact of including the long-lookahead rows.
- **The judge is named** (ChatGPT, GPT-5.6 Sol) and the prompt is reproduced in
  the appendix, so the adjudication can be repeated.

## Open

- No confidence intervals anywhere. The right resampling unit is the phrase, so
  a phrase-clustered bootstrap over the central comparisons is the obvious
  remaining statistical work.
- No frequency-matched control, and pretraining frequency is assumed rather than
  counted. Those two analyses would do most to separate phrase identity from
  exposure.
- No efficiency claim is tested: no decoding scheme, no latency measurement.
- Analyses not rerun after deduplication are not reported rather than carried
  forward: the in-context replication on OLMo-3 and Qwen, the generation-label
  probe at the earliest layers, held-out-category generalisation, layer-group
  pooling, and the confidence breakdown by probe outcome.
"""

Path("notes").mkdir(exist_ok=True)
Path("notes/PAPER_BRIEF.md").write_text(md)
print("wrote notes/PAPER_BRIEF.md")
